version: '3.8'

services:
#  nginx:
#    build: ./nginx
#    volumes:
#      - ./nginx:/usr/src/app/nginx
#    ports:
#      - 1337:80
#      - 1338:443
#    depends_on:
#      - web
  redis:
    image: redis
    ports:
      - 6379:6379
  postgresql:
    image: postgres
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB= ${DB_NAME}
      - POSTGRES_USER= ${DB_USER}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Telegram_newsletter.wsgi:application -b 0.0.0.0:8000 --reload
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
      - redis
    ports:
      - 8000:8000
  celery:
    build: ./
    command:
      - celery --app=Telegram_newsletter worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis
  bot_app:
    build:
      context: ./tg_bot/
      dockerfile: Dockerfile
    volumes:
      - ./tg_bot:/usr/src/app/tg_bot
    depends_on:
      - web
      - redis
      - celery
