version: '3.8'

services:

  postgresql:
    image: postgres
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB= ${DB_NAME}
      - POSTGRES_USER= ${DB_USER}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python /usr/src/app/manage.py migrate
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
    ports:
      - 8000:8000
